services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: web-frontend:7
    init: true
    volumes:
      - type: bind
        source: ../frontend/
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 5173:5173
    environment:
      OTEL_SERVICE_NAME: api-backend
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    networks:
      - app-network
    depends_on:
      - backend
      - db
      - jaeger
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: api-backend:7
    init: true
    volumes:
      - type: bind
        source: ../backend/
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    volumes:
      - ../database/create.sql:/docker-entrypoint-initdb.d/init.sql
      - type: volume
        target: /var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    networks:
      - app-network
  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
