import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import routes from "./routes";
dotenv.config();
const app = express();
app.use(express.json());
app.use(cors());
app.use("/", routes);
console.log("Server running on http://localhost:3000");
app.listen(3000);
